---
# --------------------------------

- name: 'add Sublime Text repo key'
  apt_key:
    url: 'https://download.sublimetext.com/sublimehq-pub.gpg'
    validate_certs: true
    state: present
  become: true
  tags:
  - sublime
  - sublime-repo
  - x-repo

- name: 'add Sublime Text repository to APT'
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    state: present
    update_cache: true
    filename: sublime
  become: true
  tags:
  - sublime
  - sublime-repo
  - x-repo

- name: 'update apt cache and install Sublime Text'
  apt:
    name: 'sublime-text'
    update_cache: true
    state: present
  become: true
  tags:
  - sublime
  - sublime-pkg
  - x-pkg

# --------------------------------
...
