---
- name: 'add GPG signing key for the Sublime Text repo'
  apt_key:
    url: '{{sublime_gpg}}'
    validate_certs: true
    state: present
  become: true
  tags:
  - ct-sublime
  - ct-sublime-repo

- name: 'add Sublime Text repository to APT'
  apt_repository:
    repo: '{{sublime_repo}}'
    state: present
    update_cache: true
    filename: sublime
  register: reg_repo
  become: true
  tags:
  - ct-sublime
  - ct-sublime-repo

- name: 'update apt cache and install Sublime Text'
  apt:
    name: '{{sublime_pkg}}'
    update_cache: '{{reg_repo is changed}}'
    state: '{{sublime_state}}'
  become: true
  tags:
  - ct-sublime
  - ct-sublime-pkg
...
